project_id = "wdw-planner"

[api]
enabled = true
port = 55321
schemas = ["public", "graphql_public"]

[db]
port = 55322
major_version = 17

[studio]
enabled = true
port = 55323

[analytics]
enabled = true
port = 55327

[local_smtp]
enabled = true
port = 55324

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["http://127.0.0.1:3000/auth/callback"]
jwt_expiry = 3600
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false
